-- Ask Me bot: FAQs + customer enquiry threads (isolated from visitors/leads).

CREATE TABLE IF NOT EXISTS public.website_bot_faqs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  gym_id uuid NOT NULL REFERENCES public.gyms(id) ON DELETE CASCADE,
  question text NOT NULL,
  answer text NOT NULL,
  sort_order int NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_website_bot_faqs_gym
  ON public.website_bot_faqs (gym_id, sort_order);

CREATE TABLE IF NOT EXISTS public.website_bot_threads (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  gym_id uuid NOT NULL REFERENCES public.gyms(id) ON DELETE CASCADE,
  public_token uuid NOT NULL DEFAULT gen_random_uuid(),
  customer_name text NOT NULL,
  mobile text NOT NULL,
  email text,
  status text NOT NULL DEFAULT 'open'
    CHECK (status IN ('open', 'answered', 'closed')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (gym_id, public_token)
);

CREATE INDEX IF NOT EXISTS idx_website_bot_threads_gym_updated
  ON public.website_bot_threads (gym_id, updated_at DESC);

CREATE INDEX IF NOT EXISTS idx_website_bot_threads_gym_mobile
  ON public.website_bot_threads (gym_id, mobile);

CREATE TABLE IF NOT EXISTS public.website_bot_messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  gym_id uuid NOT NULL REFERENCES public.gyms(id) ON DELETE CASCADE,
  thread_id bigint NOT NULL REFERENCES public.website_bot_threads(id) ON DELETE CASCADE,
  sender text NOT NULL CHECK (sender IN ('customer', 'staff', 'bot')),
  body text NOT NULL,
  staff_name text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_website_bot_messages_thread
  ON public.website_bot_messages (thread_id, created_at);

ALTER TABLE public.website_bot_faqs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.website_bot_threads ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.website_bot_messages ENABLE ROW LEVEL SECURITY;

-- No direct anon table access; all via SECURITY DEFINER RPCs.
DROP POLICY IF EXISTS website_bot_faqs_deny ON public.website_bot_faqs;
CREATE POLICY website_bot_faqs_deny ON public.website_bot_faqs
  FOR ALL TO anon, authenticated USING (false) WITH CHECK (false);

DROP POLICY IF EXISTS website_bot_threads_deny ON public.website_bot_threads;
CREATE POLICY website_bot_threads_deny ON public.website_bot_threads
  FOR ALL TO anon, authenticated USING (false) WITH CHECK (false);

DROP POLICY IF EXISTS website_bot_messages_deny ON public.website_bot_messages;
CREATE POLICY website_bot_messages_deny ON public.website_bot_messages
  FOR ALL TO anon, authenticated USING (false) WITH CHECK (false);

-- Seed default FAQs for Action Plus Gym (idempotent per gym).
INSERT INTO public.website_bot_faqs (gym_id, question, answer, sort_order, is_active)
SELECT g.id, v.question, v.answer, v.sort_order, true
FROM public.gyms g
CROSS JOIN (
  VALUES
    (0, 'What are your opening hours?',
     'We are open Monday to Saturday, 6:00 AM – 9:30 PM. Sunday is closed. Check the Hours section on our site for today''s highlight.'),
    (1, 'Where are you located?',
     'Action Plus Gym & Fitness Club — Subhas Nagar, near Jaipal Store, Subhas Nagar Board, Adra, West Bengal 723121. You can find us on the Contact page map.'),
    (2, 'Do you offer a free trial?',
     'Yes — tap Free Trial on our Join form or Contact page, leave your details, and our team will arrange a trial session for you.'),
    (3, 'How do I start a membership?',
     'Use Join Now on the website or visit the gym. Our team will help you pick a plan (Monthly, Quarterly, or Yearly) and get you started.'),
    (4, 'How can I contact the gym?',
     'Call +91 70471 57510, WhatsApp us from the site buttons, email gymactionplus@gmail.com, or submit a query in this chat — we reply here.'),
    (5, 'What facilities do you have?',
     'Strength training, cardio, guided coaching, and a focused training environment in Adra. Explore Services and Trainers on the homepage for more.')
) AS v(sort_order, question, answer)
WHERE g.id = '48815df4-6144-40dd-bbd6-91fd8522d1ff'::uuid
  AND NOT EXISTS (
    SELECT 1 FROM public.website_bot_faqs f WHERE f.gym_id = g.id
  );

-- Public: list active FAQs
CREATE OR REPLACE FUNCTION public.website_bot_list_faqs(p_gym_id uuid)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_rows jsonb;
BEGIN
  SELECT COALESCE(jsonb_agg(
    jsonb_build_object(
      'id', f.id,
      'question', f.question,
      'answer', f.answer,
      'sort_order', f.sort_order
    ) ORDER BY f.sort_order, f.id
  ), '[]'::jsonb)
  INTO v_rows
  FROM website_bot_faqs f
  WHERE f.gym_id = p_gym_id
    AND f.is_active = true;

  RETURN jsonb_build_object('ok', true, 'faqs', v_rows);
END;
$$;

-- Public: submit enquiry (creates thread + first customer message)
CREATE OR REPLACE FUNCTION public.website_bot_submit_enquiry(
  p_gym_id uuid,
  p_full_name text,
  p_mobile text,
  p_message text,
  p_email text DEFAULT NULL,
  p_public_token uuid DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_thread website_bot_threads%ROWTYPE;
  v_token uuid;
BEGIN
  IF p_full_name IS NULL OR length(trim(p_full_name)) < 2 THEN
    RETURN jsonb_build_object('ok', false, 'error', 'Name required');
  END IF;
  IF p_mobile IS NULL OR length(trim(p_mobile)) < 6 THEN
    RETURN jsonb_build_object('ok', false, 'error', 'Mobile required');
  END IF;
  IF p_message IS NULL OR length(trim(p_message)) < 2 THEN
    RETURN jsonb_build_object('ok', false, 'error', 'Message required');
  END IF;

  v_token := COALESCE(p_public_token, gen_random_uuid());

  SELECT * INTO v_thread
  FROM website_bot_threads
  WHERE gym_id = p_gym_id
    AND public_token = v_token
  LIMIT 1;

  IF FOUND THEN
    UPDATE website_bot_threads SET
      customer_name = trim(p_full_name),
      mobile = trim(p_mobile),
      email = NULLIF(trim(COALESCE(p_email, '')), ''),
      status = 'open',
      updated_at = now()
    WHERE id = v_thread.id
    RETURNING * INTO v_thread;
  ELSE
    INSERT INTO website_bot_threads (
      gym_id, public_token, customer_name, mobile, email, status
    ) VALUES (
      p_gym_id,
      v_token,
      trim(p_full_name),
      trim(p_mobile),
      NULLIF(trim(COALESCE(p_email, '')), ''),
      'open'
    )
    RETURNING * INTO v_thread;
  END IF;

  INSERT INTO website_bot_messages (gym_id, thread_id, sender, body)
  VALUES (p_gym_id, v_thread.id, 'customer', trim(p_message));

  RETURN jsonb_build_object(
    'ok', true,
    'public_token', v_thread.public_token,
    'thread_id', v_thread.id
  );
END;
$$;

-- Public: get thread by token, or latest for mobile under same gym
CREATE OR REPLACE FUNCTION public.website_bot_get_thread(
  p_gym_id uuid,
  p_public_token uuid DEFAULT NULL,
  p_mobile text DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_thread website_bot_threads%ROWTYPE;
  v_msgs jsonb;
BEGIN
  IF p_public_token IS NOT NULL THEN
    SELECT * INTO v_thread
    FROM website_bot_threads
    WHERE gym_id = p_gym_id
      AND public_token = p_public_token
    LIMIT 1;
  ELSIF p_mobile IS NOT NULL AND length(trim(p_mobile)) >= 6 THEN
    SELECT * INTO v_thread
    FROM website_bot_threads
    WHERE gym_id = p_gym_id
      AND mobile = trim(p_mobile)
    ORDER BY updated_at DESC
    LIMIT 1;
  ELSE
    RETURN jsonb_build_object('ok', false, 'error', 'Token or mobile required');
  END IF;

  IF NOT FOUND THEN
    RETURN jsonb_build_object('ok', false, 'error', 'Conversation not found');
  END IF;

  SELECT COALESCE(jsonb_agg(
    jsonb_build_object(
      'id', m.id,
      'sender', m.sender,
      'body', m.body,
      'staff_name', m.staff_name,
      'created_at', m.created_at
    ) ORDER BY m.created_at, m.id
  ), '[]'::jsonb)
  INTO v_msgs
  FROM website_bot_messages m
  WHERE m.thread_id = v_thread.id;

  RETURN jsonb_build_object(
    'ok', true,
    'thread', jsonb_build_object(
      'id', v_thread.id,
      'public_token', v_thread.public_token,
      'customer_name', v_thread.customer_name,
      'mobile', v_thread.mobile,
      'email', v_thread.email,
      'status', v_thread.status,
      'created_at', v_thread.created_at,
      'updated_at', v_thread.updated_at
    ),
    'messages', v_msgs
  );
END;
$$;

-- Admin: list threads
CREATE OR REPLACE FUNCTION public.website_bot_admin_list_threads(p_token text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_staff record;
  v_rows jsonb;
BEGIN
  SELECT * INTO v_staff FROM website_session_staff(p_token);
  IF NOT FOUND THEN RETURN jsonb_build_object('ok', false, 'error', 'Unauthorized'); END IF;

  SELECT COALESCE(jsonb_agg(to_jsonb(t) ORDER BY
    CASE t.status WHEN 'open' THEN 0 WHEN 'answered' THEN 1 ELSE 2 END,
    t.updated_at DESC
  ), '[]'::jsonb)
  INTO v_rows
  FROM (
    SELECT
      th.id,
      th.public_token,
      th.customer_name,
      th.mobile,
      th.email,
      th.status,
      th.created_at,
      th.updated_at,
      (
        SELECT left(m.body, 120)
        FROM website_bot_messages m
        WHERE m.thread_id = th.id
        ORDER BY m.created_at DESC
        LIMIT 1
      ) AS last_message,
      (
        SELECT count(*)::int
        FROM website_bot_messages m
        WHERE m.thread_id = th.id AND m.sender = 'customer'
      ) AS customer_message_count
    FROM website_bot_threads th
    WHERE th.gym_id = v_staff.gym_id
    ORDER BY
      CASE th.status WHEN 'open' THEN 0 WHEN 'answered' THEN 1 ELSE 2 END,
      th.updated_at DESC
    LIMIT 200
  ) t;

  RETURN jsonb_build_object('ok', true, 'threads', v_rows);
END;
$$;

-- Admin: get one thread + messages
CREATE OR REPLACE FUNCTION public.website_bot_admin_get_thread(
  p_token text,
  p_thread_id bigint
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_staff record;
  v_thread website_bot_threads%ROWTYPE;
  v_msgs jsonb;
BEGIN
  SELECT * INTO v_staff FROM website_session_staff(p_token);
  IF NOT FOUND THEN RETURN jsonb_build_object('ok', false, 'error', 'Unauthorized'); END IF;

  SELECT * INTO v_thread
  FROM website_bot_threads
  WHERE id = p_thread_id
    AND gym_id = v_staff.gym_id
  LIMIT 1;

  IF NOT FOUND THEN
    RETURN jsonb_build_object('ok', false, 'error', 'Not found');
  END IF;

  SELECT COALESCE(jsonb_agg(
    jsonb_build_object(
      'id', m.id,
      'sender', m.sender,
      'body', m.body,
      'staff_name', m.staff_name,
      'created_at', m.created_at
    ) ORDER BY m.created_at, m.id
  ), '[]'::jsonb)
  INTO v_msgs
  FROM website_bot_messages m
  WHERE m.thread_id = v_thread.id;

  RETURN jsonb_build_object(
    'ok', true,
    'thread', to_jsonb(v_thread),
    'messages', v_msgs
  );
END;
$$;

-- Admin: reply as Action Plus Gym
CREATE OR REPLACE FUNCTION public.website_bot_admin_reply(
  p_token text,
  p_thread_id bigint,
  p_body text
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_staff record;
  v_thread website_bot_threads%ROWTYPE;
BEGIN
  SELECT * INTO v_staff FROM website_session_staff(p_token);
  IF NOT FOUND THEN RETURN jsonb_build_object('ok', false, 'error', 'Unauthorized'); END IF;

  IF p_body IS NULL OR length(trim(p_body)) < 1 THEN
    RETURN jsonb_build_object('ok', false, 'error', 'Reply required');
  END IF;

  SELECT * INTO v_thread
  FROM website_bot_threads
  WHERE id = p_thread_id
    AND gym_id = v_staff.gym_id
  LIMIT 1;

  IF NOT FOUND THEN
    RETURN jsonb_build_object('ok', false, 'error', 'Not found');
  END IF;

  INSERT INTO website_bot_messages (gym_id, thread_id, sender, body, staff_name)
  VALUES (
    v_staff.gym_id,
    v_thread.id,
    'staff',
    trim(p_body),
    COALESCE(NULLIF(trim(v_staff.full_name), ''), v_staff.staff_login_id, 'Action Plus Gym')
  );

  UPDATE website_bot_threads SET
    status = 'answered',
    updated_at = now()
  WHERE id = v_thread.id;

  RETURN jsonb_build_object('ok', true);
END;
$$;

-- Admin: list all FAQs (including inactive)
CREATE OR REPLACE FUNCTION public.website_bot_admin_list_faqs(p_token text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_staff record;
  v_rows jsonb;
BEGIN
  SELECT * INTO v_staff FROM website_session_staff(p_token);
  IF NOT FOUND THEN RETURN jsonb_build_object('ok', false, 'error', 'Unauthorized'); END IF;

  SELECT COALESCE(jsonb_agg(to_jsonb(f) ORDER BY f.sort_order, f.id), '[]'::jsonb)
  INTO v_rows
  FROM website_bot_faqs f
  WHERE f.gym_id = v_staff.gym_id;

  RETURN jsonb_build_object('ok', true, 'faqs', v_rows);
END;
$$;

-- Admin: replace FAQ set
CREATE OR REPLACE FUNCTION public.website_bot_admin_save_faqs(
  p_token text,
  p_faqs jsonb
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_staff record;
  r jsonb;
  v_i int := 0;
BEGIN
  SELECT * INTO v_staff FROM website_session_staff(p_token);
  IF NOT FOUND THEN RETURN jsonb_build_object('ok', false, 'error', 'Unauthorized'); END IF;

  DELETE FROM website_bot_faqs WHERE gym_id = v_staff.gym_id;

  IF p_faqs IS NULL OR jsonb_typeof(p_faqs) <> 'array' THEN
    RETURN jsonb_build_object('ok', true, 'count', 0);
  END IF;

  FOR r IN SELECT * FROM jsonb_array_elements(p_faqs)
  LOOP
    IF coalesce(trim(r->>'question'), '') = '' OR coalesce(trim(r->>'answer'), '') = '' THEN
      CONTINUE;
    END IF;
    INSERT INTO website_bot_faqs (
      gym_id, question, answer, sort_order, is_active, updated_at
    ) VALUES (
      v_staff.gym_id,
      trim(r->>'question'),
      trim(r->>'answer'),
      coalesce((r->>'sort_order')::int, v_i),
      coalesce((r->>'is_active')::boolean, true),
      now()
    );
    v_i := v_i + 1;
  END LOOP;

  RETURN jsonb_build_object('ok', true, 'count', v_i);
END;
$$;

GRANT EXECUTE ON FUNCTION public.website_bot_list_faqs(uuid) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.website_bot_submit_enquiry(uuid, text, text, text, text, uuid) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.website_bot_get_thread(uuid, uuid, text) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.website_bot_admin_list_threads(text) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.website_bot_admin_get_thread(text, bigint) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.website_bot_admin_reply(text, bigint, text) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.website_bot_admin_list_faqs(text) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.website_bot_admin_save_faqs(text, jsonb) TO anon, authenticated;
