import type { SiteContent } from "@/lib/types";
import { GYM_ID } from "@/lib/config";

export const fallbackContent: SiteContent = {
  settings: {
    gym_id: GYM_ID,
    site_name: "Action Plus Gym",
    tagline: "Train Harder. Live Stronger.",
    phone: "+91 90000 00000",
    email: "info@actionplusgym.com",
    whatsapp: "919000000000",
    address: "Action Plus Gym, Adra, West Bengal, India",
    map_embed_url: "",
    google_reviews_url: "https://www.google.com/maps",
    timezone: "Asia/Kolkata",
    socials: {
      instagram: "https://instagram.com",
      facebook: "https://facebook.com",
      youtube: "https://youtube.com",
    },
    seo_title: "Action Plus Gym | Premium Fitness Club",
    seo_description:
      "Premium gym training, personal coaching, and world-class facilities at Action Plus Gym.",
    seo_og_image:
      "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=1200&q=80",
    hero_headline: "Elevate Your Limits",
    hero_subheadline:
      "Premium coaching, elite equipment, and a membership experience built for results.",
  },
  sections: {
    hero: true,
    stats: true,
    services: true,
    pricing: true,
    trainers: true,
    gallery: true,
    videos: true,
    testimonials: true,
    hours: true,
    reviews: true,
    contact: true,
    popup: true,
    footer: true,
  },
  popup: {
    id: 1,
    enabled: true,
    title: "7 Day Free Trial",
    body: "Experience Action Plus with complimentary access. No joining fee this month.",
    image_url:
      "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=1200&q=80",
    button_text: "Book Free Trial",
    button_href: "#join",
    bg_color: "#0A0A0A",
    accent_color: "#C9A227",
    text_color: "#FFFFFF",
    expires_at: null,
  },
  heroSlides: [
    {
      id: 1,
      title: "Strength",
      image_url:
        "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=2000&q=80",
      video_url: "",
      sort_order: 0,
      is_active: true,
    },
    {
      id: 2,
      title: "Performance",
      image_url:
        "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=2000&q=80",
      video_url: "",
      sort_order: 1,
      is_active: true,
    },
  ],
  stats: [
    { id: 1, label: "Members", value: "2,500+", sort_order: 0 },
    { id: 2, label: "Trainers", value: "25+", sort_order: 1 },
    { id: 3, label: "Years Experience", value: "12+", sort_order: 2 },
    { id: 4, label: "Google Rating", value: "4.9", sort_order: 3 },
  ],
  services: [
    {
      id: 1,
      title: "Personal Training",
      description: "One-to-one coaching tailored to your goals.",
      icon: "dumbbell",
      image_url: "",
      sort_order: 0,
      is_active: true,
    },
    {
      id: 2,
      title: "Group Classes",
      description: "High-energy sessions that keep you accountable.",
      icon: "users",
      image_url: "",
      sort_order: 1,
      is_active: true,
    },
    {
      id: 3,
      title: "Strength Training",
      description: "Build power with premium free weights and machines.",
      icon: "zap",
      image_url: "",
      sort_order: 2,
      is_active: true,
    },
    {
      id: 4,
      title: "Weight Loss",
      description: "Sustainable fat-loss programs with expert guidance.",
      icon: "trending-down",
      image_url: "",
      sort_order: 3,
      is_active: true,
    },
    {
      id: 5,
      title: "Cardio",
      description: "Endurance zones designed for every level.",
      icon: "heart",
      image_url: "",
      sort_order: 4,
      is_active: true,
    },
    {
      id: 6,
      title: "Functional Training",
      description: "Move better for sport and everyday life.",
      icon: "activity",
      image_url: "",
      sort_order: 5,
      is_active: true,
    },
    {
      id: 7,
      title: "CrossFit",
      description: "High-intensity functional fitness for athletes.",
      icon: "flame",
      image_url: "",
      sort_order: 6,
      is_active: true,
    },
    {
      id: 8,
      title: "Nutrition",
      description: "Fuel your training with practical nutrition plans.",
      icon: "apple",
      image_url: "",
      sort_order: 7,
      is_active: true,
    },
    {
      id: 9,
      title: "Body Building",
      description: "Hypertrophy-focused programming and coaching.",
      icon: "trophy",
      image_url: "",
      sort_order: 8,
      is_active: true,
    },
    {
      id: 10,
      title: "Ladies Fitness",
      description: "Supportive training spaces and coaching for women.",
      icon: "sparkles",
      image_url: "",
      sort_order: 9,
      is_active: true,
    },
  ],
  pricing: [
    {
      id: 1,
      name: "Monthly",
      period: "monthly",
      price: "₹1,499",
      description: "Flexible month-to-month access.",
      features: ["Full gym access", "Group classes", "Locker rooms"],
      is_featured: false,
      badge: "",
      cta_text: "Join Now",
      sort_order: 0,
      is_active: true,
    },
    {
      id: 2,
      name: "Quarterly",
      period: "quarterly",
      price: "₹3,999",
      description: "Best balance of value and commitment.",
      features: [
        "Full gym access",
        "Group classes",
        "1 PT session",
        "Guest pass",
      ],
      is_featured: true,
      badge: "Most Popular",
      cta_text: "Join Now",
      sort_order: 1,
      is_active: true,
    },
    {
      id: 3,
      name: "Yearly",
      period: "yearly",
      price: "₹12,999",
      description: "Maximum savings for serious athletes.",
      features: [
        "Full gym access",
        "All classes",
        "4 PT sessions",
        "Priority booking",
      ],
      is_featured: false,
      badge: "Best Value",
      cta_text: "Join Now",
      sort_order: 2,
      is_active: true,
    },
  ],
  trainers: [
    {
      id: 1,
      name: "Alex Morgan",
      photo_url:
        "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=800&q=80",
      experience: "8 years",
      specialization: "Strength & Conditioning",
      bio: "Elite strength coach focused on form and progressive overload.",
      socials: {},
      sort_order: 0,
      is_active: true,
    },
    {
      id: 2,
      name: "Jordan Lee",
      photo_url:
        "https://images.unsplash.com/photo-1594381898411-846e7d193883?w=800&q=80",
      experience: "6 years",
      specialization: "Weight Loss",
      bio: "Transforms habits with accountability and sustainable programming.",
      socials: {},
      sort_order: 1,
      is_active: true,
    },
    {
      id: 3,
      name: "Sam Rivera",
      photo_url:
        "https://images.unsplash.com/photo-1549476464-37392f717541?w=800&q=80",
      experience: "10 years",
      specialization: "Athletic Performance",
      bio: "Former athlete helping members move with power and precision.",
      socials: {},
      sort_order: 2,
      is_active: true,
    },
  ],
  albums: [],
  gallery: [
    {
      id: 1,
      album_id: null,
      image_url:
        "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=1200&q=80",
      alt_text: "Gym floor",
      sort_order: 0,
      is_active: true,
    },
    {
      id: 2,
      album_id: null,
      image_url:
        "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=1200&q=80",
      alt_text: "Training",
      sort_order: 1,
      is_active: true,
    },
    {
      id: 3,
      album_id: null,
      image_url:
        "https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=1200&q=80",
      alt_text: "Weights",
      sort_order: 2,
      is_active: true,
    },
    {
      id: 4,
      album_id: null,
      image_url:
        "https://images.unsplash.com/photo-1540497077202-7c8a3999166f?w=1200&q=80",
      alt_text: "Studio",
      sort_order: 3,
      is_active: true,
    },
  ],
  videos: [
    {
      id: 1,
      title: "Club Tour",
      youtube_url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
      mp4_url: "",
      thumbnail_url:
        "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&q=80",
      sort_order: 0,
      is_active: true,
    },
  ],
  testimonials: [
    {
      id: 1,
      name: "Priya S.",
      quote:
        "The coaching culture here is unmatched. I finally have a plan that works.",
      rating: 5,
      photo_url:
        "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&q=80",
      video_url: "",
      sort_order: 0,
      is_active: true,
    },
    {
      id: 2,
      name: "Marcus T.",
      quote:
        "Premium facility with people who actually care about your progress.",
      rating: 5,
      photo_url:
        "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&q=80",
      video_url: "",
      sort_order: 1,
      is_active: true,
    },
    {
      id: 3,
      name: "Elena R.",
      quote:
        "Joined for the free trial and never looked back. Best decision this year.",
      rating: 5,
      photo_url:
        "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&q=80",
      video_url: "",
      sort_order: 2,
      is_active: true,
    },
  ],
  hours: [
    {
      id: 1,
      day_of_week: 1,
      open_time: "05:00:00",
      close_time: "22:00:00",
      is_closed: false,
      is_hidden: false,
    },
    {
      id: 2,
      day_of_week: 2,
      open_time: "05:00:00",
      close_time: "22:00:00",
      is_closed: false,
      is_hidden: false,
    },
    {
      id: 3,
      day_of_week: 3,
      open_time: "05:00:00",
      close_time: "22:00:00",
      is_closed: false,
      is_hidden: false,
    },
    {
      id: 4,
      day_of_week: 4,
      open_time: "05:00:00",
      close_time: "22:00:00",
      is_closed: false,
      is_hidden: false,
    },
    {
      id: 5,
      day_of_week: 5,
      open_time: "05:00:00",
      close_time: "22:00:00",
      is_closed: false,
      is_hidden: false,
    },
    {
      id: 6,
      day_of_week: 6,
      open_time: "06:00:00",
      close_time: "20:00:00",
      is_closed: false,
      is_hidden: false,
    },
    {
      id: 7,
      day_of_week: 0,
      open_time: "08:00:00",
      close_time: "18:00:00",
      is_closed: false,
      is_hidden: false,
    },
  ],
  reviews: {
    overall_rating: 4.8,
    total_reviews: 138,
    google_url:
      "https://www.google.com/search?q=Action+Plus+Gym+and+Fitness+Club+Reviews",
    reviews: [
      {
        author: "ABHIJIT HAZRA",
        rating: 5,
        text: "Clean, well-equipped gym with a friendly management team. Kaushik my trainer deserve special Kudoz for being patient and for coming up with all technical tips regarding forms and details. Excellent experience!",
        relative_time: "5 months ago",
      },
      {
        author: "Subhadeep Bayen",
        rating: 5,
        text: "Action Plus Gym is an excellent place for fitness enthusiasts. The environment is positive and motivating, and my trainer Kaushik is very friendly and supportive. Highly recommended!",
        relative_time: "8 months ago",
      },
      {
        author: "Mahima Gupta",
        rating: 5,
        text: "Best gym in Adra. And the trainer of this gym guide you if you don’t know anything. The gym is well clean and maintained.",
        relative_time: "4 months ago",
      },
      {
        author: "Vaishali Kumari",
        rating: 5,
        text: "I had a great experience at this gym! The environment is very motivating and well-maintained, with all the necessary equipment. Special mention to Koushik Bhaiya — highly recommend.",
        relative_time: "1 year ago",
      },
      {
        author: "Bishal Yadav",
        rating: 5,
        text: "Best gym in Adra. So all fitness lovers come and join.",
        relative_time: "4 months ago",
      },
      {
        author: "Sakshi Ranjan",
        rating: 5,
        text: "Too good experience. Nice gym. I recommend — go ahead!",
        relative_time: "4 months ago",
      },
      {
        author: "Soumya Kanti Acharya",
        rating: 5,
        text: "This gym sets the gold standard with top-tier equipment and expert trainers. Every workout here feels like a step closer to greatness. One of the best gyms in Adra.",
        relative_time: "1 year ago",
      },
      {
        author: "Subhajit De",
        rating: 5,
        text: "Nice place, nice trainers, awesome environment — thumbs up from my side.",
        relative_time: "Recent",
      },
      {
        author: "Tanmay Bouri",
        rating: 5,
        text: "The gym is full of advanced equipment. Trainers are very nice.",
        relative_time: "Recent",
      },
      {
        author: "SUBRATA MONDAL",
        rating: 5,
        text: "Well maintained and all members behave politely. I am proud that I do workout in that gym.",
        relative_time: "Recent",
      },
    ],
  },
};
